var searchData=
[
  ['daemon_0',['Daemon',['../d3/d5f/classdoris_1_1_daemon.html',1,'doris']]],
  ['data_1',['Data',['../db/d13/structdoris_1_1internal_1_1gscoped__ptr__impl_1_1_data.html',1,'doris::internal::gscoped_ptr_impl']]],
  ['databinding_2',['DataBinding',['../de/de1/structdoris_1_1_data_binding.html',1,'doris']]],
  ['dataconsumer_3',['DataConsumer',['../d9/db1/classdoris_1_1_data_consumer.html',1,'doris']]],
  ['dataconsumergroup_4',['DataConsumerGroup',['../d2/d59/classdoris_1_1_data_consumer_group.html',1,'doris']]],
  ['dataconsumerpool_5',['DataConsumerPool',['../db/d61/classdoris_1_1_data_consumer_pool.html',1,'doris']]],
  ['datadir_6',['DataDir',['../d2/df7/classdoris_1_1_data_dir.html',1,'doris']]],
  ['datadirinfo_7',['DataDirInfo',['../dc/d90/structdoris_1_1_data_dir_info.html',1,'doris']]],
  ['datadirinfolessavailability_8',['DataDirInfoLessAvailability',['../d8/d63/structdoris_1_1_data_dir_info_less_availability.html',1,'doris']]],
  ['datagenoperator_9',['DataGenOperator',['../d8/ddf/classdoris_1_1pipeline_1_1_data_gen_operator.html',1,'doris::pipeline']]],
  ['datagenoperatorbuilder_10',['DataGenOperatorBuilder',['../d9/d1d/classdoris_1_1pipeline_1_1_data_gen_operator_builder.html',1,'doris::pipeline']]],
  ['datapagepredecoder_11',['DataPagePreDecoder',['../de/de7/classdoris_1_1segment__v2_1_1_data_page_pre_decoder.html',1,'doris::segment_v2']]],
  ['dataqueue_12',['DataQueue',['../d2/daf/classdoris_1_1pipeline_1_1_data_queue.html',1,'doris::pipeline']]],
  ['datasink_13',['DataSink',['../d8/d90/classdoris_1_1_data_sink.html',1,'doris']]],
  ['datasinkoperator_14',['DataSinkOperator',['../d0/d34/classdoris_1_1pipeline_1_1_data_sink_operator.html',1,'doris::pipeline']]],
  ['datasinkoperator_3c_20exchangesinkoperatorbuilder_20_3e_15',['DataSinkOperator&lt; ExchangeSinkOperatorBuilder &gt;',['../d0/d34/classdoris_1_1pipeline_1_1_data_sink_operator.html',1,'doris::pipeline']]],
  ['datasinkoperator_3c_20olaptablesinkoperatorbuilder_20_3e_16',['DataSinkOperator&lt; OlapTableSinkOperatorBuilder &gt;',['../d0/d34/classdoris_1_1pipeline_1_1_data_sink_operator.html',1,'doris::pipeline']]],
  ['datasinkoperator_3c_20resultfilesinkoperatorbuilder_20_3e_17',['DataSinkOperator&lt; ResultFileSinkOperatorBuilder &gt;',['../d0/d34/classdoris_1_1pipeline_1_1_data_sink_operator.html',1,'doris::pipeline']]],
  ['datasinkoperator_3c_20resultsinkoperatorbuilder_20_3e_18',['DataSinkOperator&lt; ResultSinkOperatorBuilder &gt;',['../d0/d34/classdoris_1_1pipeline_1_1_data_sink_operator.html',1,'doris::pipeline']]],
  ['datasinkoperator_3c_20tablesinkoperatorbuilder_20_3e_19',['DataSinkOperator&lt; TableSinkOperatorBuilder &gt;',['../d0/d34/classdoris_1_1pipeline_1_1_data_sink_operator.html',1,'doris::pipeline']]],
  ['datasinkoperatorbuilder_20',['DataSinkOperatorBuilder',['../da/d9f/classdoris_1_1pipeline_1_1_data_sink_operator_builder.html',1,'doris::pipeline']]],
  ['datasinkoperatorbuilder_3c_20stream_5fload_3a_3avolaptablesink_20_3e_21',['DataSinkOperatorBuilder&lt; stream_load::VOlapTableSink &gt;',['../da/d9f/classdoris_1_1pipeline_1_1_data_sink_operator_builder.html',1,'doris::pipeline']]],
  ['datasinkoperatorbuilder_3c_20vectorized_3a_3avdatastreamsender_20_3e_22',['DataSinkOperatorBuilder&lt; vectorized::VDataStreamSender &gt;',['../da/d9f/classdoris_1_1pipeline_1_1_data_sink_operator_builder.html',1,'doris::pipeline']]],
  ['datasinkoperatorbuilder_3c_20vectorized_3a_3avresultfilesink_20_3e_23',['DataSinkOperatorBuilder&lt; vectorized::VResultFileSink &gt;',['../da/d9f/classdoris_1_1pipeline_1_1_data_sink_operator_builder.html',1,'doris::pipeline']]],
  ['datasinkoperatorbuilder_3c_20vectorized_3a_3avresultsink_20_3e_24',['DataSinkOperatorBuilder&lt; vectorized::VResultSink &gt;',['../da/d9f/classdoris_1_1pipeline_1_1_data_sink_operator_builder.html',1,'doris::pipeline']]],
  ['datasinkoperatorbuilder_3c_20vectorized_3a_3avtablesink_20_3e_25',['DataSinkOperatorBuilder&lt; vectorized::VTableSink &gt;',['../da/d9f/classdoris_1_1pipeline_1_1_data_sink_operator_builder.html',1,'doris::pipeline']]],
  ['datatypearray_26',['DataTypeArray',['../de/d17/classdoris_1_1vectorized_1_1_data_type_array.html',1,'doris::vectorized']]],
  ['datatypebitmap_27',['DataTypeBitMap',['../d9/ddd/classdoris_1_1vectorized_1_1_data_type_bit_map.html',1,'doris::vectorized']]],
  ['datatypedate_28',['DataTypeDate',['../d2/d4c/classdoris_1_1vectorized_1_1_data_type_date.html',1,'doris::vectorized']]],
  ['datatypedatetime_29',['DataTypeDateTime',['../d7/df9/classdoris_1_1vectorized_1_1_data_type_date_time.html',1,'doris::vectorized']]],
  ['datatypedatetimev2_30',['DataTypeDateTimeV2',['../db/d12/classdoris_1_1vectorized_1_1_data_type_date_time_v2.html',1,'doris::vectorized']]],
  ['datatypedatev2_31',['DataTypeDateV2',['../db/d63/classdoris_1_1vectorized_1_1_data_type_date_v2.html',1,'doris::vectorized']]],
  ['datatypedecimal_32',['DataTypeDecimal',['../d2/d45/classdoris_1_1vectorized_1_1_data_type_decimal.html',1,'doris::vectorized']]],
  ['datatypeenum_33',['DataTypeEnum',['../d3/d18/classdoris_1_1vectorized_1_1_data_type_enum.html',1,'doris::vectorized']]],
  ['datatypefactory_34',['DataTypeFactory',['../d2/db6/classdoris_1_1vectorized_1_1_data_type_factory.html',1,'doris::vectorized']]],
  ['datatypefixedlengthobject_35',['DataTypeFixedLengthObject',['../d0/d51/classdoris_1_1vectorized_1_1_data_type_fixed_length_object.html',1,'doris::vectorized']]],
  ['datatypehll_36',['DataTypeHLL',['../db/d7a/classdoris_1_1vectorized_1_1_data_type_h_l_l.html',1,'doris::vectorized']]],
  ['datatypejsonb_37',['DataTypeJsonb',['../df/dff/classdoris_1_1vectorized_1_1_data_type_jsonb.html',1,'doris::vectorized']]],
  ['datatypemap_38',['DataTypeMap',['../dd/d10/classdoris_1_1vectorized_1_1_data_type_map.html',1,'doris::vectorized']]],
  ['datatypenothing_39',['DataTypeNothing',['../db/db5/classdoris_1_1vectorized_1_1_data_type_nothing.html',1,'doris::vectorized']]],
  ['datatypenullable_40',['DataTypeNullable',['../d2/d73/classdoris_1_1vectorized_1_1_data_type_nullable.html',1,'doris::vectorized']]],
  ['datatypenumber_41',['DataTypeNumber',['../dc/db2/classdoris_1_1vectorized_1_1_data_type_number.html',1,'doris::vectorized']]],
  ['datatypenumberbase_42',['DataTypeNumberBase',['../d1/dcb/classdoris_1_1vectorized_1_1_data_type_number_base.html',1,'doris::vectorized']]],
  ['datatypenumberbase_3c_20float64_20_3e_43',['DataTypeNumberBase&lt; Float64 &gt;',['../d1/dcb/classdoris_1_1vectorized_1_1_data_type_number_base.html',1,'doris::vectorized']]],
  ['datatypenumberbase_3c_20int64_20_3e_44',['DataTypeNumberBase&lt; Int64 &gt;',['../d1/dcb/classdoris_1_1vectorized_1_1_data_type_number_base.html',1,'doris::vectorized']]],
  ['datatypenumberbase_3c_20uint32_20_3e_45',['DataTypeNumberBase&lt; UInt32 &gt;',['../d1/dcb/classdoris_1_1vectorized_1_1_data_type_number_base.html',1,'doris::vectorized']]],
  ['datatypenumberbase_3c_20uint64_20_3e_46',['DataTypeNumberBase&lt; UInt64 &gt;',['../d1/dcb/classdoris_1_1vectorized_1_1_data_type_number_base.html',1,'doris::vectorized']]],
  ['datatypeobject_47',['DataTypeObject',['../de/d95/classdoris_1_1vectorized_1_1_data_type_object.html',1,'doris::vectorized']]],
  ['datatypequantilestate_48',['DataTypeQuantileState',['../de/d63/classdoris_1_1vectorized_1_1_data_type_quantile_state.html',1,'doris::vectorized']]],
  ['datatypestring_49',['DataTypeString',['../d5/d91/classdoris_1_1vectorized_1_1_data_type_string.html',1,'doris::vectorized']]],
  ['datatypestruct_50',['DataTypeStruct',['../d6/db5/classdoris_1_1vectorized_1_1_data_type_struct.html',1,'doris::vectorized']]],
  ['datatypetime_51',['DataTypeTime',['../db/dee/classdoris_1_1vectorized_1_1_data_type_time.html',1,'doris::vectorized']]],
  ['datefindop_52',['DateFindOp',['../dd/d9b/structdoris_1_1_date_find_op.html',1,'doris']]],
  ['dateformatimpl_53',['DateFormatImpl',['../df/df9/structdoris_1_1vectorized_1_1_date_format_impl.html',1,'doris::vectorized']]],
  ['dateimpl_54',['DateImpl',['../d5/d4b/structdoris_1_1vectorized_1_1_date_impl.html',1,'doris::vectorized']]],
  ['datetimeaddintervalimpl_55',['DateTimeAddIntervalImpl',['../d3/de7/structdoris_1_1vectorized_1_1_date_time_add_interval_impl.html',1,'doris::vectorized']]],
  ['datetimefindop_56',['DateTimeFindOp',['../de/d3c/structdoris_1_1_date_time_find_op.html',1,'doris']]],
  ['datetimeop_57',['DateTimeOp',['../d5/da0/structdoris_1_1vectorized_1_1_date_time_op.html',1,'doris::vectorized']]],
  ['datetimetransformimpl_58',['DateTimeTransformImpl',['../db/d91/structdoris_1_1vectorized_1_1_date_time_transform_impl.html',1,'doris::vectorized']]],
  ['datetimev2uint64union_59',['DateTimeV2UInt64Union',['../df/d28/uniondoris_1_1_date_time_v2_u_int64_union.html',1,'doris']]],
  ['datetimev2valuetype_60',['DateTimeV2ValueType',['../da/d27/structdoris_1_1vectorized_1_1_date_time_v2_value_type.html',1,'doris::vectorized']]],
  ['datetraits_61',['DateTraits',['../d2/d97/structdoris_1_1vectorized_1_1_date_traits.html',1,'doris::vectorized']]],
  ['datetraits_3c_20int64_5ft_20_3e_62',['DateTraits&lt; int64_t &gt;',['../d1/da6/structdoris_1_1vectorized_1_1_date_traits_3_01int64__t_01_4.html',1,'doris::vectorized']]],
  ['datetraits_3c_20uint32_5ft_20_3e_63',['DateTraits&lt; uint32_t &gt;',['../de/dd7/structdoris_1_1vectorized_1_1_date_traits_3_01uint32__t_01_4.html',1,'doris::vectorized']]],
  ['datetraits_3c_20uint64_5ft_20_3e_64',['DateTraits&lt; uint64_t &gt;',['../dd/d96/structdoris_1_1vectorized_1_1_date_traits_3_01uint64__t_01_4.html',1,'doris::vectorized']]],
  ['datetrunc_65',['DateTrunc',['../de/d55/structdoris_1_1vectorized_1_1_date_trunc.html',1,'doris::vectorized']]],
  ['datev2uint32union_66',['DateV2UInt32Union',['../d5/d29/uniondoris_1_1_date_v2_u_int32_union.html',1,'doris']]],
  ['datev2value_67',['DateV2Value',['../d8/d34/classdoris_1_1vectorized_1_1_date_v2_value.html',1,'doris::vectorized']]],
  ['datev2value_3c_20doris_3a_3avectorized_3a_3adatetimev2valuetype_20_3e_68',['DateV2Value&lt; doris::vectorized::DateTimeV2ValueType &gt;',['../d8/d34/classdoris_1_1vectorized_1_1_date_v2_value.html',1,'doris::vectorized']]],
  ['datev2value_3c_20doris_3a_3avectorized_3a_3adatev2valuetype_20_3e_69',['DateV2Value&lt; doris::vectorized::DateV2ValueType &gt;',['../d8/d34/classdoris_1_1vectorized_1_1_date_v2_value.html',1,'doris::vectorized']]],
  ['datev2valuetype_70',['DateV2ValueType',['../dc/dad/structdoris_1_1vectorized_1_1_date_v2_value_type.html',1,'doris::vectorized']]],
  ['daynameimpl_71',['DayNameImpl',['../d0/d7b/structdoris_1_1vectorized_1_1_day_name_impl.html',1,'doris::vectorized']]],
  ['dcheckasserter_72',['DCheckAsserter',['../d7/df9/structbase_1_1_d_check_asserter.html',1,'base']]],
  ['dcontext_73',['DContext',['../db/d3e/structdoris_1_1_lz4f_block_compression_1_1_d_context.html',1,'Lz4fBlockCompression::DContext'],['../db/db3/structdoris_1_1_zstd_block_compression_1_1_d_context.html',1,'ZstdBlockCompression::DContext']]],
  ['debugruntimeprofile_74',['DebugRuntimeProfile',['../d5/da6/classdoris_1_1_debug_runtime_profile.html',1,'doris']]],
  ['deccompareint_75',['DecCompareInt',['../db/df8/structdoris_1_1vectorized_1_1_dec_compare_int.html',1,'doris::vectorized']]],
  ['deccompareint_3c_20a_2c_20b_20_3e_76',['DecCompareInt&lt; A, B &gt;',['../db/df8/structdoris_1_1vectorized_1_1_dec_compare_int.html',1,'doris::vectorized']]],
  ['decimal_77',['Decimal',['../da/d29/structdoris_1_1vectorized_1_1_decimal.html',1,'doris::vectorized']]],
  ['decimal12_5ft_78',['decimal12_t',['../de/d00/structdoris_1_1decimal12__t.html',1,'doris']]],
  ['decimal_3c_20int128_20_3e_79',['Decimal&lt; Int128 &gt;',['../da/d29/structdoris_1_1vectorized_1_1_decimal.html',1,'doris::vectorized']]],
  ['decimal_3c_20int128i_20_3e_80',['Decimal&lt; Int128I &gt;',['../dc/d67/structdoris_1_1vectorized_1_1_decimal_3_01_int128_i_01_4.html',1,'doris::vectorized']]],
  ['decimalbinaryoperation_81',['DecimalBinaryOperation',['../d1/d7f/structdoris_1_1vectorized_1_1_decimal_binary_operation.html',1,'doris::vectorized']]],
  ['decimalcomparison_82',['DecimalComparison',['../d6/d42/classdoris_1_1vectorized_1_1_decimal_comparison.html',1,'doris::vectorized']]],
  ['decimalfield_83',['DecimalField',['../d5/d27/classdoris_1_1vectorized_1_1_decimal_field.html',1,'doris::vectorized']]],
  ['decimalint128union_84',['DecimalInt128Union',['../d9/dfa/uniondoris_1_1_decimal_int128_union.html',1,'doris']]],
  ['decimalpaddedpodarray_85',['DecimalPaddedPODArray',['../dd/dd5/classdoris_1_1vectorized_1_1_decimal_padded_p_o_d_array.html',1,'doris::vectorized']]],
  ['decimalpredicatecreator_86',['DecimalPredicateCreator',['../d9/d50/classdoris_1_1_decimal_predicate_creator.html',1,'doris']]],
  ['decimalroundingimpl_87',['DecimalRoundingImpl',['../db/de4/classdoris_1_1vectorized_1_1_decimal_rounding_impl.html',1,'doris::vectorized']]],
  ['decimalroundoneimpl_88',['DecimalRoundOneImpl',['../d1/d67/structdoris_1_1vectorized_1_1_decimal_round_one_impl.html',1,'doris::vectorized']]],
  ['decimalroundtwoimpl_89',['DecimalRoundTwoImpl',['../d9/d6a/structdoris_1_1vectorized_1_1_decimal_round_two_impl.html',1,'doris::vectorized']]],
  ['decimalscaleparams_90',['DecimalScaleParams',['../d1/d15/structdoris_1_1vectorized_1_1_decimal_scale_params.html',1,'doris::vectorized']]],
  ['decimalv2findop_91',['DecimalV2FindOp',['../de/d86/structdoris_1_1_decimal_v2_find_op.html',1,'doris']]],
  ['decimalv2value_92',['DecimalV2Value',['../d1/d52/classdoris_1_1_decimal_v2_value.html',1,'doris']]],
  ['decodeparams_93',['DecodeParams',['../da/d9e/structdoris_1_1vectorized_1_1_decode_params.html',1,'doris::vectorized']]],
  ['decoder_94',['Decoder',['../d6/d88/classdoris_1_1vectorized_1_1_decoder.html',1,'doris::vectorized']]],
  ['decompressor_95',['Decompressor',['../d5/d9a/classdoris_1_1_decompressor.html',1,'doris']]],
  ['decryptimpl_96',['DecryptImpl',['../d4/de0/structdoris_1_1vectorized_1_1_decrypt_impl.html',1,'doris::vectorized']]],
  ['defaultdeleter_97',['DefaultDeleter',['../d9/dbb/structdoris_1_1_default_deleter.html',1,'doris']]],
  ['defaultdeleter_3c_20t_5b_5d_3e_98',['DefaultDeleter&lt; T[]&gt;',['../df/dc7/structdoris_1_1_default_deleter_3_01_t_0f_0e_4.html',1,'doris']]],
  ['defaultdeleter_3c_20t_5bn_5d_3e_99',['DefaultDeleter&lt; T[n]&gt;',['../da/dbe/structdoris_1_1_default_deleter_3_01_t_0fn_0e_4.html',1,'doris']]],
  ['defaultexecutable_100',['DefaultExecutable',['../df/d33/classdoris_1_1vectorized_1_1_default_executable.html',1,'doris::vectorized']]],
  ['defaultfunction_101',['DefaultFunction',['../d7/dce/classdoris_1_1vectorized_1_1_default_function.html',1,'doris::vectorized']]],
  ['defaultfunctionbuilder_102',['DefaultFunctionBuilder',['../d0/dd7/classdoris_1_1vectorized_1_1_default_function_builder.html',1,'doris::vectorized']]],
  ['defaulthash_103',['DefaultHash',['../d4/d27/struct_default_hash.html',1,'']]],
  ['defaulthash_3c_20doris_3a_3astringref_20_3e_104',['DefaultHash&lt; doris::StringRef &gt;',['../d6/d95/struct_default_hash_3_01doris_1_1_string_ref_01_4.html',1,'']]],
  ['defaulthash_3c_20doris_3a_3avectorized_3a_3aint128i_20_3e_105',['DefaultHash&lt; doris::vectorized::Int128I &gt;',['../d5/d2e/struct_default_hash_3_01doris_1_1vectorized_1_1_int128_i_01_4.html',1,'']]],
  ['defaulthash_3c_20elementnativetype_20_3e_106',['DefaultHash&lt; ElementNativeType &gt;',['../d4/d27/struct_default_hash.html',1,'']]],
  ['defaulthash_3c_20elementtype_20_3e_107',['DefaultHash&lt; ElementType &gt;',['../d4/d27/struct_default_hash.html',1,'']]],
  ['defaulthash_3c_20key_20_3e_108',['DefaultHash&lt; Key &gt;',['../d4/d27/struct_default_hash.html',1,'']]],
  ['defaulthash_3c_20stringref_20_3e_109',['DefaultHash&lt; StringRef &gt;',['../d4/d27/struct_default_hash.html',1,'']]],
  ['defaulthash_3c_20t_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5farithmetic_5fv_3c_20t_20_3e_20_3e_20_3e_110',['DefaultHash&lt; T, std::enable_if_t&lt; std::is_arithmetic_v&lt; T &gt; &gt; &gt;',['../de/d1e/struct_default_hash_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__v_3_01_t_01_4_01_4_01_4.html',1,'']]],
  ['defaultrefcountedthreadsafetraits_111',['DefaultRefCountedThreadSafeTraits',['../df/d02/structdoris_1_1_default_ref_counted_thread_safe_traits.html',1,'doris']]],
  ['defaultvaluecolumniterator_112',['DefaultValueColumnIterator',['../d4/df6/classdoris_1_1segment__v2_1_1_default_value_column_iterator.html',1,'doris::segment_v2']]],
  ['defer_113',['Defer',['../d8/d40/classdoris_1_1_defer.html',1,'doris']]],
  ['deferredconstructedregexps_114',['DeferredConstructedRegexps',['../d4/d6e/classdoris_1_1vectorized_1_1multiregexps_1_1_deferred_constructed_regexps.html',1,'doris::vectorized::multiregexps']]],
  ['degreesimpl_115',['DegreesImpl',['../d1/df5/structdoris_1_1vectorized_1_1_degrees_impl.html',1,'doris::vectorized']]],
  ['deletebitmap_116',['DeleteBitmap',['../d6/d6d/classdoris_1_1_delete_bitmap.html',1,'doris']]],
  ['deleteconditions_117',['DeleteConditions',['../d7/d69/structdoris_1_1_delete_conditions.html',1,'doris']]],
  ['deletehandler_118',['DeleteHandler',['../d6/d23/classdoris_1_1_delete_handler.html',1,'doris']]],
  ['deleter_119',['Deleter',['../d1/d4f/structdoris_1_1vectorized_1_1_simple_object_pool_1_1_deleter.html',1,'doris::vectorized::SimpleObjectPool']]],
  ['deltabitpackdecoder_120',['DeltaBitPackDecoder',['../d4/d8a/classdoris_1_1vectorized_1_1_delta_bit_pack_decoder.html',1,'doris::vectorized']]],
  ['deltabitpackdecoder_3c_20int32_5ft_20_3e_121',['DeltaBitPackDecoder&lt; int32_t &gt;',['../d4/d8a/classdoris_1_1vectorized_1_1_delta_bit_pack_decoder.html',1,'doris::vectorized']]],
  ['deltabytearraydecoder_122',['DeltaByteArrayDecoder',['../d6/dec/classdoris_1_1vectorized_1_1_delta_byte_array_decoder.html',1,'doris::vectorized']]],
  ['deltadecoder_123',['DeltaDecoder',['../d8/df2/classdoris_1_1vectorized_1_1_delta_decoder.html',1,'doris::vectorized']]],
  ['deltalengthbytearraydecoder_124',['DeltaLengthByteArrayDecoder',['../de/d96/classdoris_1_1vectorized_1_1_delta_length_byte_array_decoder.html',1,'doris::vectorized']]],
  ['deltawriter_125',['DeltaWriter',['../d7/d75/classdoris_1_1_delta_writer.html',1,'doris']]],
  ['denserankdata_126',['DenseRankData',['../d2/dda/structdoris_1_1vectorized_1_1_dense_rank_data.html',1,'doris::vectorized']]],
  ['derivedcounter_127',['DerivedCounter',['../da/d23/classdoris_1_1_runtime_profile_1_1_derived_counter.html',1,'doris::RuntimeProfile']]],
  ['descriptortbl_128',['DescriptorTbl',['../da/d43/classdoris_1_1_descriptor_tbl.html',1,'doris']]],
  ['dfastate_129',['DFAState',['../d3/d35/structdoris_1_1vectorized_1_1_aggregate_function_sequence_match_data_1_1_d_f_a_state.html',1,'doris::vectorized::AggregateFunctionSequenceMatchData']]],
  ['dictionary_130',['Dictionary',['../d6/db5/classdoris_1_1vectorized_1_1_column_dictionary_1_1_dictionary.html',1,'doris::vectorized::ColumnDictionary']]],
  ['disk_131',['Disk',['../d0/dcd/structdoris_1_1_disk_info_1_1_disk.html',1,'doris::DiskInfo']]],
  ['diskinfo_132',['DiskInfo',['../d2/ddb/classdoris_1_1_disk_info.html',1,'doris']]],
  ['diskmetrics_133',['DiskMetrics',['../db/dc3/structdoris_1_1_disk_metrics.html',1,'doris']]],
  ['dispatcher_134',['Dispatcher',['../d9/dfb/structdoris_1_1vectorized_1_1_dispatcher.html',1,'doris::vectorized']]],
  ['dividefloatingimpl_135',['DivideFloatingImpl',['../d6/d96/structdoris_1_1vectorized_1_1_divide_floating_impl.html',1,'doris::vectorized']]],
  ['divideintegralimpl_136',['DivideIntegralImpl',['../df/d69/structdoris_1_1vectorized_1_1_divide_integral_impl.html',1,'doris::vectorized']]],
  ['dorisawslogger_137',['DorisAWSLogger',['../d4/d71/classdoris_1_1_doris_a_w_s_logger.html',1,'doris']]],
  ['doriscallonce_138',['DorisCallOnce',['../df/d24/classdoris_1_1_doris_call_once.html',1,'doris']]],
  ['doriscallonce_3c_20doris_3a_3astatus_20_3e_139',['DorisCallOnce&lt; doris::Status &gt;',['../df/d24/classdoris_1_1_doris_call_once.html',1,'doris']]],
  ['doriscompounddirectory_140',['DorisCompoundDirectory',['../d8/de8/classdoris_1_1segment__v2_1_1_doris_compound_directory.html',1,'doris::segment_v2']]],
  ['doriscompoundfilewriter_141',['DorisCompoundFileWriter',['../dd/d10/classdoris_1_1segment__v2_1_1_doris_compound_file_writer.html',1,'doris::segment_v2']]],
  ['doriscompoundreader_142',['DorisCompoundReader',['../dc/df7/classdoris_1_1segment__v2_1_1_doris_compound_reader.html',1,'doris::segment_v2']]],
  ['dorismetrics_143',['DorisMetrics',['../d3/d7b/classdoris_1_1_doris_metrics.html',1,'doris']]],
  ['dorisnodesinfo_144',['DorisNodesInfo',['../d6/dc6/classdoris_1_1_doris_nodes_info.html',1,'doris']]],
  ['doublerangeoptions_145',['DoubleRangeOptions',['../df/dbf/struct_double_range_options.html',1,'']]],
  ['doubleroundoneimpl_146',['DoubleRoundOneImpl',['../d7/db4/structdoris_1_1vectorized_1_1_double_round_one_impl.html',1,'doris::vectorized']]],
  ['doubleroundtwoimpl_147',['DoubleRoundTwoImpl',['../d5/dd8/structdoris_1_1vectorized_1_1_double_round_two_impl.html',1,'doris::vectorized']]],
  ['downloadaction_148',['DownloadAction',['../d7/d26/classdoris_1_1_download_action.html',1,'doris']]],
  ['dummyfilecache_149',['DummyFileCache',['../de/d4a/classdoris_1_1io_1_1_dummy_file_cache.html',1,'doris::io']]],
  ['dummyfileinfo_150',['DummyFileInfo',['../dc/d62/structdoris_1_1io_1_1_dummy_file_cache_1_1_dummy_file_info.html',1,'doris::io::DummyFileCache']]],
  ['dynamiccontainer_151',['DynamicContainer',['../d1/db4/classdoris_1_1_dynamic_container.html',1,'doris']]],
  ['dynamiccontainer_3c_20std_3a_3astring_20_3e_152',['DynamicContainer&lt; std::string &gt;',['../d1/db4/classdoris_1_1_dynamic_container.html',1,'doris']]],
  ['dynamiccontainer_3c_20stringref_20_3e_153',['DynamicContainer&lt; StringRef &gt;',['../d1/db4/classdoris_1_1_dynamic_container.html',1,'doris']]],
  ['dynamiccontainer_3c_20typename_20vecprimitivetypetraits_3c_20t_20_3e_3a_3acpptype_20_3e_154',['DynamicContainer&lt; typename VecPrimitiveTypeTraits&lt; T &gt;::CppType &gt;',['../d1/db4/classdoris_1_1_dynamic_container.html',1,'doris']]]
];
