var searchData=
[
  ['absimpl_0',['AbsImpl',['../d2/de9/structdoris_1_1vectorized_1_1_abs_impl.html',1,'doris::vectorized']]],
  ['acceptnullpredicate_1',['AcceptNullPredicate',['../d0/d70/classdoris_1_1_accept_null_predicate.html',1,'doris']]],
  ['acosname_2',['AcosName',['../d3/deb/structdoris_1_1vectorized_1_1_acos_name.html',1,'doris::vectorized']]],
  ['acquirelist_3',['AcquireList',['../d7/d09/structdoris_1_1vectorized_1_1_acquire_list.html',1,'doris::vectorized']]],
  ['actionimpl_4',['ActionImpl',['../dd/d51/structdoris_1_1vectorized_1_1_action_impl.html',1,'doris::vectorized']]],
  ['actionimpl_3c_20set_2c_20element_2c_20setoperation_3a_3aexcept_20_3e_5',['ActionImpl&lt; Set, Element, SetOperation::EXCEPT &gt;',['../d4/dea/structdoris_1_1vectorized_1_1_action_impl_3_01_set_00_01_element_00_01_set_operation_1_1_e_x_c_e_p_t_01_4.html',1,'doris::vectorized']]],
  ['actionimpl_3c_20set_2c_20element_2c_20setoperation_3a_3aintersect_20_3e_6',['ActionImpl&lt; Set, Element, SetOperation::INTERSECT &gt;',['../d4/d71/structdoris_1_1vectorized_1_1_action_impl_3_01_set_00_01_element_00_01_set_operation_1_1_i_n_t_e_r_s_e_c_t_01_4.html',1,'doris::vectorized']]],
  ['actionimpl_3c_20set_2c_20element_2c_20setoperation_3a_3aunion_20_3e_7',['ActionImpl&lt; Set, Element, SetOperation::UNION &gt;',['../df/d13/structdoris_1_1vectorized_1_1_action_impl_3_01_set_00_01_element_00_01_set_operation_1_1_u_n_i_o_n_01_4.html',1,'doris::vectorized']]],
  ['actionimpl_3c_20set_2c_20stringref_2c_20operation_20_3e_8',['ActionImpl&lt; Set, StringRef, operation &gt;',['../dd/d51/structdoris_1_1vectorized_1_1_action_impl.html',1,'doris::vectorized']]],
  ['addbatchcounter_9',['AddBatchCounter',['../d2/d3f/structdoris_1_1stream__load_1_1_add_batch_counter.html',1,'doris::stream_load']]],
  ['addquartersimpl_10',['AddQuartersImpl',['../df/d9d/structdoris_1_1vectorized_1_1_add_quarters_impl.html',1,'doris::vectorized']]],
  ['addthreadmemtrackerconsumer_11',['AddThreadMemTrackerConsumer',['../d2/daf/classdoris_1_1_add_thread_mem_tracker_consumer.html',1,'doris']]],
  ['aesdecryptname_12',['AESDecryptName',['../de/dde/structdoris_1_1vectorized_1_1_a_e_s_decrypt_name.html',1,'doris::vectorized']]],
  ['aesencryptname_13',['AESEncryptName',['../dc/d3e/structdoris_1_1vectorized_1_1_a_e_s_encrypt_name.html',1,'doris::vectorized']]],
  ['agentserver_14',['AgentServer',['../d5/dff/classdoris_1_1_agent_server.html',1,'doris']]],
  ['agentutils_15',['AgentUtils',['../d8/d68/classdoris_1_1_agent_utils.html',1,'doris']]],
  ['aggcache_16',['AggCache',['../d7/d8e/classdoris_1_1_delete_bitmap_1_1_agg_cache.html',1,'doris::DeleteBitmap']]],
  ['aggfnevaluator_17',['AggFnEvaluator',['../d7/da1/classdoris_1_1vectorized_1_1_agg_fn_evaluator.html',1,'doris::vectorized']]],
  ['aggfunctionorthbitmapfunc_18',['AggFunctionOrthBitmapFunc',['../da/dd5/classdoris_1_1vectorized_1_1_agg_function_orth_bitmap_func.html',1,'doris::vectorized']]],
  ['aggintersectcount_19',['AggIntersectCount',['../d5/dd3/structdoris_1_1vectorized_1_1_agg_intersect_count.html',1,'doris::vectorized']]],
  ['aggorthbitmapbasedata_20',['AggOrthBitmapBaseData',['../d4/d38/structdoris_1_1vectorized_1_1_agg_orth_bitmap_base_data.html',1,'doris::vectorized']]],
  ['aggorthbitmapexprcal_21',['AggOrthBitMapExprCal',['../de/dc6/structdoris_1_1vectorized_1_1_agg_orth_bit_map_expr_cal.html',1,'doris::vectorized']]],
  ['aggorthbitmapexprcalbasedata_22',['AggOrthBitmapExprCalBaseData',['../d4/d8f/structdoris_1_1vectorized_1_1_agg_orth_bitmap_expr_cal_base_data.html',1,'doris::vectorized']]],
  ['aggorthbitmapexprcalcount_23',['AggOrthBitMapExprCalCount',['../d2/ddc/structdoris_1_1vectorized_1_1_agg_orth_bit_map_expr_cal_count.html',1,'doris::vectorized']]],
  ['aggorthbitmapintersect_24',['AggOrthBitMapIntersect',['../d5/d44/structdoris_1_1vectorized_1_1_agg_orth_bit_map_intersect.html',1,'doris::vectorized']]],
  ['aggorthbitmapintersectcount_25',['AggOrthBitMapIntersectCount',['../d1/d20/structdoris_1_1vectorized_1_1_agg_orth_bit_map_intersect_count.html',1,'doris::vectorized']]],
  ['aggregatedatacontainer_26',['AggregateDataContainer',['../d2/da4/structdoris_1_1vectorized_1_1_aggregate_data_container.html',1,'doris::vectorized']]],
  ['aggregateddatavariants_27',['AggregatedDataVariants',['../d1/dab/structdoris_1_1vectorized_1_1_aggregated_data_variants.html',1,'doris::vectorized']]],
  ['aggregatefunction_28',['AggregateFunction',['../d5/d0d/structdoris_1_1vectorized_1_1_aggregate_function.html',1,'doris::vectorized']]],
  ['aggregatefunction_3c_20aggregatefunctionimpl_3c_20aggregateoperation_3a_3amax_20_3e_20_3e_29',['AggregateFunction&lt; AggregateFunctionImpl&lt; AggregateOperation::MAX &gt; &gt;',['../da/d8e/structdoris_1_1vectorized_1_1_aggregate_function_3_01_aggregate_function_impl_3_01_aggregate_operation_1_1_m_a_x_01_4_01_4.html',1,'doris::vectorized']]],
  ['aggregatefunction_3c_20aggregatefunctionimpl_3c_20aggregateoperation_3a_3amin_20_3e_20_3e_30',['AggregateFunction&lt; AggregateFunctionImpl&lt; AggregateOperation::MIN &gt; &gt;',['../de/d3b/structdoris_1_1vectorized_1_1_aggregate_function_3_01_aggregate_function_impl_3_01_aggregate_operation_1_1_m_i_n_01_4_01_4.html',1,'doris::vectorized']]],
  ['aggregatefunctionanydata_31',['AggregateFunctionAnyData',['../db/df5/structdoris_1_1vectorized_1_1_aggregate_function_any_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionapproxcountdistinct_32',['AggregateFunctionApproxCountDistinct',['../dc/d93/classdoris_1_1vectorized_1_1_aggregate_function_approx_count_distinct.html',1,'doris::vectorized']]],
  ['aggregatefunctionapproxcountdistinctdata_33',['AggregateFunctionApproxCountDistinctData',['../d6/ddf/structdoris_1_1vectorized_1_1_aggregate_function_approx_count_distinct_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionavg_34',['AggregateFunctionAvg',['../df/d79/classdoris_1_1vectorized_1_1_aggregate_function_avg.html',1,'doris::vectorized']]],
  ['aggregatefunctionavgdata_35',['AggregateFunctionAvgData',['../d5/df5/structdoris_1_1vectorized_1_1_aggregate_function_avg_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionavgweight_36',['AggregateFunctionAvgWeight',['../dd/d29/classdoris_1_1vectorized_1_1_aggregate_function_avg_weight.html',1,'doris::vectorized']]],
  ['aggregatefunctionavgweighteddata_37',['AggregateFunctionAvgWeightedData',['../dd/d27/structdoris_1_1vectorized_1_1_aggregate_function_avg_weighted_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionbasedata_38',['AggregateFunctionBaseData',['../dc/d45/structdoris_1_1vectorized_1_1_aggregate_function_base_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionbitmapcount_39',['AggregateFunctionBitmapCount',['../d9/d0d/classdoris_1_1vectorized_1_1_aggregate_function_bitmap_count.html',1,'doris::vectorized']]],
  ['aggregatefunctionbitmapdata_40',['AggregateFunctionBitmapData',['../df/d13/structdoris_1_1vectorized_1_1_aggregate_function_bitmap_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionbitmapintersectop_41',['AggregateFunctionBitmapIntersectOp',['../d7/d15/structdoris_1_1vectorized_1_1_aggregate_function_bitmap_intersect_op.html',1,'doris::vectorized']]],
  ['aggregatefunctionbitmapop_42',['AggregateFunctionBitmapOp',['../d5/dd3/classdoris_1_1vectorized_1_1_aggregate_function_bitmap_op.html',1,'doris::vectorized']]],
  ['aggregatefunctionbitmapunionop_43',['AggregateFunctionBitmapUnionOp',['../d6/d6c/structdoris_1_1vectorized_1_1_aggregate_function_bitmap_union_op.html',1,'doris::vectorized']]],
  ['aggregatefunctionbitwise_44',['AggregateFunctionBitwise',['../dc/d02/classdoris_1_1vectorized_1_1_aggregate_function_bitwise.html',1,'doris::vectorized']]],
  ['aggregatefunctioncollect_45',['AggregateFunctionCollect',['../d4/d09/classdoris_1_1vectorized_1_1_aggregate_function_collect.html',1,'doris::vectorized']]],
  ['aggregatefunctioncollectlistdata_46',['AggregateFunctionCollectListData',['../d8/d53/structdoris_1_1vectorized_1_1_aggregate_function_collect_list_data.html',1,'doris::vectorized']]],
  ['aggregatefunctioncollectlistdata_3c_20stringref_2c_20haslimit_20_3e_47',['AggregateFunctionCollectListData&lt; StringRef, HasLimit &gt;',['../da/d92/structdoris_1_1vectorized_1_1_aggregate_function_collect_list_data_3_01_string_ref_00_01_has_limit_01_4.html',1,'doris::vectorized']]],
  ['aggregatefunctioncollectsetdata_48',['AggregateFunctionCollectSetData',['../dc/d92/structdoris_1_1vectorized_1_1_aggregate_function_collect_set_data.html',1,'doris::vectorized']]],
  ['aggregatefunctioncollectsetdata_3c_20stringref_2c_20haslimit_20_3e_49',['AggregateFunctionCollectSetData&lt; StringRef, HasLimit &gt;',['../d6/ddb/structdoris_1_1vectorized_1_1_aggregate_function_collect_set_data_3_01_string_ref_00_01_has_limit_01_4.html',1,'doris::vectorized']]],
  ['aggregatefunctioncombinatordistinct_50',['AggregateFunctionCombinatorDistinct',['../d5/d98/classdoris_1_1vectorized_1_1_aggregate_function_combinator_distinct.html',1,'doris::vectorized']]],
  ['aggregatefunctioncount_51',['AggregateFunctionCount',['../d0/d08/classdoris_1_1vectorized_1_1_aggregate_function_count.html',1,'doris::vectorized']]],
  ['aggregatefunctioncountdata_52',['AggregateFunctionCountData',['../d9/dd9/structdoris_1_1vectorized_1_1_aggregate_function_count_data.html',1,'doris::vectorized']]],
  ['aggregatefunctioncountnotnullunary_53',['AggregateFunctionCountNotNullUnary',['../de/d31/classdoris_1_1vectorized_1_1_aggregate_function_count_not_null_unary.html',1,'doris::vectorized']]],
  ['aggregatefunctiondistinct_54',['AggregateFunctionDistinct',['../d5/d48/classdoris_1_1vectorized_1_1_aggregate_function_distinct.html',1,'doris::vectorized']]],
  ['aggregatefunctiondistinctgenericdata_55',['AggregateFunctionDistinctGenericData',['../d3/d96/structdoris_1_1vectorized_1_1_aggregate_function_distinct_generic_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiondistinctmultiplegenericdata_56',['AggregateFunctionDistinctMultipleGenericData',['../d9/d16/structdoris_1_1vectorized_1_1_aggregate_function_distinct_multiple_generic_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiondistinctsinglegenericdata_57',['AggregateFunctionDistinctSingleGenericData',['../df/d2f/structdoris_1_1vectorized_1_1_aggregate_function_distinct_single_generic_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiondistinctsinglenumericdata_58',['AggregateFunctionDistinctSingleNumericData',['../d6/d0c/structdoris_1_1vectorized_1_1_aggregate_function_distinct_single_numeric_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiongroupbitanddata_59',['AggregateFunctionGroupBitAndData',['../d4/d96/structdoris_1_1vectorized_1_1_aggregate_function_group_bit_and_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiongroupbitmapxorop_60',['AggregateFunctionGroupBitmapXorOp',['../d6/d49/structdoris_1_1vectorized_1_1_aggregate_function_group_bitmap_xor_op.html',1,'doris::vectorized']]],
  ['aggregatefunctiongroupbitordata_61',['AggregateFunctionGroupBitOrData',['../dd/d2f/structdoris_1_1vectorized_1_1_aggregate_function_group_bit_or_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiongroupbitxordata_62',['AggregateFunctionGroupBitXorData',['../d4/de7/structdoris_1_1vectorized_1_1_aggregate_function_group_bit_xor_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiongroupconcat_63',['AggregateFunctionGroupConcat',['../d4/df0/classdoris_1_1vectorized_1_1_aggregate_function_group_concat.html',1,'doris::vectorized']]],
  ['aggregatefunctiongroupconcatdata_64',['AggregateFunctionGroupConcatData',['../d9/dbf/structdoris_1_1vectorized_1_1_aggregate_function_group_concat_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiongroupconcatimplstr_65',['AggregateFunctionGroupConcatImplStr',['../d0/d3d/structdoris_1_1vectorized_1_1_aggregate_function_group_concat_impl_str.html',1,'doris::vectorized']]],
  ['aggregatefunctiongroupconcatimplstrstr_66',['AggregateFunctionGroupConcatImplStrStr',['../d2/d6b/structdoris_1_1vectorized_1_1_aggregate_function_group_concat_impl_str_str.html',1,'doris::vectorized']]],
  ['aggregatefunctionguard_67',['AggregateFunctionGuard',['../d5/d8c/classdoris_1_1vectorized_1_1_aggregate_function_guard.html',1,'doris::vectorized']]],
  ['aggregatefunctionhistogram_68',['AggregateFunctionHistogram',['../de/dac/classdoris_1_1vectorized_1_1_aggregate_function_histogram.html',1,'doris::vectorized']]],
  ['aggregatefunctionhistogramdata_69',['AggregateFunctionHistogramData',['../d1/d64/structdoris_1_1vectorized_1_1_aggregate_function_histogram_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionhlldata_70',['AggregateFunctionHLLData',['../d7/dd7/structdoris_1_1vectorized_1_1_aggregate_function_h_l_l_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionhllunion_71',['AggregateFunctionHLLUnion',['../dc/d51/classdoris_1_1vectorized_1_1_aggregate_function_h_l_l_union.html',1,'doris::vectorized']]],
  ['aggregatefunctionhllunionaggimpl_72',['AggregateFunctionHLLUnionAggImpl',['../d8/d2b/structdoris_1_1vectorized_1_1_aggregate_function_h_l_l_union_agg_impl.html',1,'doris::vectorized']]],
  ['aggregatefunctionhllunionimpl_73',['AggregateFunctionHLLUnionImpl',['../d5/d1b/structdoris_1_1vectorized_1_1_aggregate_function_h_l_l_union_impl.html',1,'doris::vectorized']]],
  ['aggregatefunctionimpl_74',['AggregateFunctionImpl',['../d5/d4a/structdoris_1_1vectorized_1_1_aggregate_function_impl.html',1,'doris::vectorized']]],
  ['aggregatefunctionimpl_3c_20aggregateoperation_3a_3aaverage_20_3e_75',['AggregateFunctionImpl&lt; AggregateOperation::AVERAGE &gt;',['../dc/d7b/structdoris_1_1vectorized_1_1_aggregate_function_impl_3_01_aggregate_operation_1_1_a_v_e_r_a_g_e_01_4.html',1,'doris::vectorized']]],
  ['aggregatefunctionimpl_3c_20aggregateoperation_3a_3aproduct_20_3e_76',['AggregateFunctionImpl&lt; AggregateOperation::PRODUCT &gt;',['../db/ddc/structdoris_1_1vectorized_1_1_aggregate_function_impl_3_01_aggregate_operation_1_1_p_r_o_d_u_c_t_01_4.html',1,'doris::vectorized']]],
  ['aggregatefunctionimpl_3c_20aggregateoperation_3a_3asum_20_3e_77',['AggregateFunctionImpl&lt; AggregateOperation::SUM &gt;',['../de/dbf/structdoris_1_1vectorized_1_1_aggregate_function_impl_3_01_aggregate_operation_1_1_s_u_m_01_4.html',1,'doris::vectorized']]],
  ['aggregatefunctionmaxbydata_78',['AggregateFunctionMaxByData',['../da/d9c/structdoris_1_1vectorized_1_1_aggregate_function_max_by_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionmaxdata_79',['AggregateFunctionMaxData',['../d2/d2c/structdoris_1_1vectorized_1_1_aggregate_function_max_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionminbydata_80',['AggregateFunctionMinByData',['../da/ddd/structdoris_1_1vectorized_1_1_aggregate_function_min_by_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionmindata_81',['AggregateFunctionMinData',['../d6/db4/structdoris_1_1vectorized_1_1_aggregate_function_min_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionminmaxbybasedata_82',['AggregateFunctionMinMaxByBaseData',['../d3/dff/structdoris_1_1vectorized_1_1_aggregate_function_min_max_by_base_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionnothing_83',['AggregateFunctionNothing',['../d8/df0/classdoris_1_1vectorized_1_1_aggregate_function_nothing.html',1,'doris::vectorized']]],
  ['aggregatefunctionnullbaseinline_84',['AggregateFunctionNullBaseInline',['../d2/d48/classdoris_1_1vectorized_1_1_aggregate_function_null_base_inline.html',1,'doris::vectorized']]],
  ['aggregatefunctionnullbaseinline_3c_20nestfuction_2c_20result_5fis_5fnullable_2c_20aggregatefunctionnullunaryinline_3c_20nestfuction_2c_20result_5fis_5fnullable_20_3e_20_3e_85',['AggregateFunctionNullBaseInline&lt; NestFuction, result_is_nullable, AggregateFunctionNullUnaryInline&lt; NestFuction, result_is_nullable &gt; &gt;',['../d2/d48/classdoris_1_1vectorized_1_1_aggregate_function_null_base_inline.html',1,'doris::vectorized']]],
  ['aggregatefunctionnullbaseinline_3c_20nestfuction_2c_20result_5fis_5fnullable_2c_20aggregatefunctionnullvariadicinline_3c_20nestfuction_2c_20result_5fis_5fnullable_20_3e_20_3e_86',['AggregateFunctionNullBaseInline&lt; NestFuction, result_is_nullable, AggregateFunctionNullVariadicInline&lt; NestFuction, result_is_nullable &gt; &gt;',['../d2/d48/classdoris_1_1vectorized_1_1_aggregate_function_null_base_inline.html',1,'doris::vectorized']]],
  ['aggregatefunctionnullunaryinline_87',['AggregateFunctionNullUnaryInline',['../d7/d5e/classdoris_1_1vectorized_1_1_aggregate_function_null_unary_inline.html',1,'doris::vectorized']]],
  ['aggregatefunctionnullvariadicinline_88',['AggregateFunctionNullVariadicInline',['../d1/da7/classdoris_1_1vectorized_1_1_aggregate_function_null_variadic_inline.html',1,'doris::vectorized']]],
  ['aggregatefunctionpercentile_89',['AggregateFunctionPercentile',['../d4/d83/classdoris_1_1vectorized_1_1_aggregate_function_percentile.html',1,'doris::vectorized']]],
  ['aggregatefunctionpercentileapprox_90',['AggregateFunctionPercentileApprox',['../dd/dae/classdoris_1_1vectorized_1_1_aggregate_function_percentile_approx.html',1,'doris::vectorized']]],
  ['aggregatefunctionpercentileapproxmerge_91',['AggregateFunctionPercentileApproxMerge',['../db/d6e/classdoris_1_1vectorized_1_1_aggregate_function_percentile_approx_merge.html',1,'doris::vectorized']]],
  ['aggregatefunctionpercentileapproxthreeparams_92',['AggregateFunctionPercentileApproxThreeParams',['../d1/dd6/classdoris_1_1vectorized_1_1_aggregate_function_percentile_approx_three_params.html',1,'doris::vectorized']]],
  ['aggregatefunctionpercentileapproxtwoparams_93',['AggregateFunctionPercentileApproxTwoParams',['../df/df1/classdoris_1_1vectorized_1_1_aggregate_function_percentile_approx_two_params.html',1,'doris::vectorized']]],
  ['aggregatefunctionpercentilearray_94',['AggregateFunctionPercentileArray',['../d3/d9d/classdoris_1_1vectorized_1_1_aggregate_function_percentile_array.html',1,'doris::vectorized']]],
  ['aggregatefunctionpop_95',['AggregateFunctionPop',['../da/d2d/classdoris_1_1vectorized_1_1_aggregate_function_pop.html',1,'doris::vectorized']]],
  ['aggregatefunctionproduct_96',['AggregateFunctionProduct',['../dd/dd1/classdoris_1_1vectorized_1_1_aggregate_function_product.html',1,'doris::vectorized']]],
  ['aggregatefunctionproductdata_97',['AggregateFunctionProductData',['../d4/dd7/structdoris_1_1vectorized_1_1_aggregate_function_product_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionproductdata_3c_20decimal128_20_3e_98',['AggregateFunctionProductData&lt; Decimal128 &gt;',['../d1/de1/structdoris_1_1vectorized_1_1_aggregate_function_product_data_3_01_decimal128_01_4.html',1,'doris::vectorized']]],
  ['aggregatefunctionproductdata_3c_20decimal128i_20_3e_99',['AggregateFunctionProductData&lt; Decimal128I &gt;',['../d0/d22/structdoris_1_1vectorized_1_1_aggregate_function_product_data_3_01_decimal128_i_01_4.html',1,'doris::vectorized']]],
  ['aggregatefunctionquantilestatedata_100',['AggregateFunctionQuantileStateData',['../db/d68/structdoris_1_1vectorized_1_1_aggregate_function_quantile_state_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionquantilestateop_101',['AggregateFunctionQuantileStateOp',['../d9/de9/classdoris_1_1vectorized_1_1_aggregate_function_quantile_state_op.html',1,'doris::vectorized']]],
  ['aggregatefunctionquantilestateunionop_102',['AggregateFunctionQuantileStateUnionOp',['../d2/d49/structdoris_1_1vectorized_1_1_aggregate_function_quantile_state_union_op.html',1,'doris::vectorized']]],
  ['aggregatefunctionretention_103',['AggregateFunctionRetention',['../d8/de7/classdoris_1_1vectorized_1_1_aggregate_function_retention.html',1,'doris::vectorized']]],
  ['aggregatefunctionsamp_104',['AggregateFunctionSamp',['../d9/d60/classdoris_1_1vectorized_1_1_aggregate_function_samp.html',1,'doris::vectorized']]],
  ['aggregatefunctionsampvariance_105',['AggregateFunctionSampVariance',['../d2/dac/classdoris_1_1vectorized_1_1_aggregate_function_samp_variance.html',1,'doris::vectorized']]],
  ['aggregatefunctionsampvariance_3c_20false_2c_20data_2c_20is_5fnullable_20_3e_106',['AggregateFunctionSampVariance&lt; false, Data, is_nullable &gt;',['../d2/dac/classdoris_1_1vectorized_1_1_aggregate_function_samp_variance.html',1,'doris::vectorized']]],
  ['aggregatefunctionsampvariance_3c_20true_2c_20data_2c_20is_5fnullable_20_3e_107',['AggregateFunctionSampVariance&lt; true, Data, is_nullable &gt;',['../d2/dac/classdoris_1_1vectorized_1_1_aggregate_function_samp_variance.html',1,'doris::vectorized']]],
  ['aggregatefunctionsequencebase_108',['AggregateFunctionSequenceBase',['../d9/d29/classdoris_1_1vectorized_1_1_aggregate_function_sequence_base.html',1,'doris::vectorized']]],
  ['aggregatefunctionsequencebase_3c_20datevaluetype_2c_20nativetype_2c_20aggregatefunctionsequencecount_3c_20datevaluetype_2c_20nativetype_20_3e_20_3e_109',['AggregateFunctionSequenceBase&lt; DateValueType, NativeType, AggregateFunctionSequenceCount&lt; DateValueType, NativeType &gt; &gt;',['../d9/d29/classdoris_1_1vectorized_1_1_aggregate_function_sequence_base.html',1,'doris::vectorized']]],
  ['aggregatefunctionsequencebase_3c_20datevaluetype_2c_20nativetype_2c_20aggregatefunctionsequencematch_3c_20datevaluetype_2c_20nativetype_20_3e_20_3e_110',['AggregateFunctionSequenceBase&lt; DateValueType, NativeType, AggregateFunctionSequenceMatch&lt; DateValueType, NativeType &gt; &gt;',['../d9/d29/classdoris_1_1vectorized_1_1_aggregate_function_sequence_base.html',1,'doris::vectorized']]],
  ['aggregatefunctionsequencecount_111',['AggregateFunctionSequenceCount',['../df/de1/classdoris_1_1vectorized_1_1_aggregate_function_sequence_count.html',1,'doris::vectorized']]],
  ['aggregatefunctionsequencematch_112',['AggregateFunctionSequenceMatch',['../d8/d59/classdoris_1_1vectorized_1_1_aggregate_function_sequence_match.html',1,'doris::vectorized']]],
  ['aggregatefunctionsequencematchdata_113',['AggregateFunctionSequenceMatchData',['../d5/df3/structdoris_1_1vectorized_1_1_aggregate_function_sequence_match_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionsimplefactory_114',['AggregateFunctionSimpleFactory',['../d6/d59/classdoris_1_1vectorized_1_1_aggregate_function_simple_factory.html',1,'doris::vectorized']]],
  ['aggregatefunctionsminmaxby_115',['AggregateFunctionsMinMaxBy',['../da/dcc/classdoris_1_1vectorized_1_1_aggregate_functions_min_max_by.html',1,'doris::vectorized']]],
  ['aggregatefunctionsort_116',['AggregateFunctionSort',['../da/d41/classdoris_1_1vectorized_1_1_aggregate_function_sort.html',1,'doris::vectorized']]],
  ['aggregatefunctionsortdata_117',['AggregateFunctionSortData',['../d5/d27/structdoris_1_1vectorized_1_1_aggregate_function_sort_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionssinglevalue_118',['AggregateFunctionsSingleValue',['../d1/d2c/classdoris_1_1vectorized_1_1_aggregate_functions_single_value.html',1,'doris::vectorized']]],
  ['aggregatefunctionstatedata_119',['AggregateFunctionStateData',['../d3/d03/structdoris_1_1vectorized_1_1_aggregate_function_state_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionsum_120',['AggregateFunctionSum',['../d1/dc6/classdoris_1_1vectorized_1_1_aggregate_function_sum.html',1,'doris::vectorized']]],
  ['aggregatefunctionsumdata_121',['AggregateFunctionSumData',['../d4/d86/structdoris_1_1vectorized_1_1_aggregate_function_sum_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiontopn_122',['AggregateFunctionTopN',['../d6/d85/classdoris_1_1vectorized_1_1_aggregate_function_top_n.html',1,'doris::vectorized']]],
  ['aggregatefunctiontopnarray_123',['AggregateFunctionTopNArray',['../da/da6/classdoris_1_1vectorized_1_1_aggregate_function_top_n_array.html',1,'doris::vectorized']]],
  ['aggregatefunctiontopnbase_124',['AggregateFunctionTopNBase',['../d3/da1/classdoris_1_1vectorized_1_1_aggregate_function_top_n_base.html',1,'doris::vectorized']]],
  ['aggregatefunctiontopnbase_3c_20impl_2c_20std_3a_3astring_20_3e_125',['AggregateFunctionTopNBase&lt; Impl, std::string &gt;',['../d3/da1/classdoris_1_1vectorized_1_1_aggregate_function_top_n_base.html',1,'doris::vectorized']]],
  ['aggregatefunctiontopndata_126',['AggregateFunctionTopNData',['../d0/dfa/structdoris_1_1vectorized_1_1_aggregate_function_top_n_data.html',1,'doris::vectorized']]],
  ['aggregatefunctiontopnimplarray_127',['AggregateFunctionTopNImplArray',['../d6/d96/structdoris_1_1vectorized_1_1_aggregate_function_top_n_impl_array.html',1,'doris::vectorized']]],
  ['aggregatefunctiontopnimplint_128',['AggregateFunctionTopNImplInt',['../d7/d0f/structdoris_1_1vectorized_1_1_aggregate_function_top_n_impl_int.html',1,'doris::vectorized']]],
  ['aggregatefunctiontopnimplintint_129',['AggregateFunctionTopNImplIntInt',['../dc/d4e/structdoris_1_1vectorized_1_1_aggregate_function_top_n_impl_int_int.html',1,'doris::vectorized']]],
  ['aggregatefunctiontopnimplweight_130',['AggregateFunctionTopNImplWeight',['../de/d10/structdoris_1_1vectorized_1_1_aggregate_function_top_n_impl_weight.html',1,'doris::vectorized']]],
  ['aggregatefunctionuniq_131',['AggregateFunctionUniq',['../d2/d54/classdoris_1_1vectorized_1_1_aggregate_function_uniq.html',1,'doris::vectorized']]],
  ['aggregatefunctionuniqexactdata_132',['AggregateFunctionUniqExactData',['../dc/d28/structdoris_1_1vectorized_1_1_aggregate_function_uniq_exact_data.html',1,'doris::vectorized']]],
  ['aggregatefunctionwindowfunnel_133',['AggregateFunctionWindowFunnel',['../d0/d6c/classdoris_1_1vectorized_1_1_aggregate_function_window_funnel.html',1,'doris::vectorized']]],
  ['aggregatejavaudaf_134',['AggregateJavaUdaf',['../d5/d72/classdoris_1_1vectorized_1_1_aggregate_java_udaf.html',1,'doris::vectorized']]],
  ['aggregatejavaudafdata_135',['AggregateJavaUdafData',['../df/db1/structdoris_1_1vectorized_1_1_aggregate_java_udaf_data.html',1,'doris::vectorized']]],
  ['aggregaterpcudaf_136',['AggregateRpcUdaf',['../dd/d0a/classdoris_1_1vectorized_1_1_aggregate_rpc_udaf.html',1,'doris::vectorized']]],
  ['aggregaterpcudafdata_137',['AggregateRpcUdafData',['../d5/de5/structdoris_1_1vectorized_1_1_aggregate_rpc_udaf_data.html',1,'doris::vectorized']]],
  ['aggregationdatawithnullkey_138',['AggregationDataWithNullKey',['../dc/d41/structdoris_1_1vectorized_1_1_aggregation_data_with_null_key.html',1,'doris::vectorized']]],
  ['aggregationmethodkeysfixed_139',['AggregationMethodKeysFixed',['../db/dd4/structdoris_1_1vectorized_1_1_aggregation_method_keys_fixed.html',1,'doris::vectorized']]],
  ['aggregationmethodonenumber_140',['AggregationMethodOneNumber',['../d5/dab/structdoris_1_1vectorized_1_1_aggregation_method_one_number.html',1,'doris::vectorized']]],
  ['aggregationmethodserialized_141',['AggregationMethodSerialized',['../d5/da9/structdoris_1_1vectorized_1_1_aggregation_method_serialized.html',1,'doris::vectorized']]],
  ['aggregationmethodsinglenullablecolumn_142',['AggregationMethodSingleNullableColumn',['../d5/d95/structdoris_1_1vectorized_1_1_aggregation_method_single_nullable_column.html',1,'doris::vectorized']]],
  ['aggregationmethodstringnocache_143',['AggregationMethodStringNoCache',['../d5/d86/structdoris_1_1vectorized_1_1_aggregation_method_string_no_cache.html',1,'doris::vectorized']]],
  ['aggregationnode_144',['AggregationNode',['../d7/d71/classdoris_1_1vectorized_1_1_aggregation_node.html',1,'doris::vectorized']]],
  ['aggsinkoperator_145',['AggSinkOperator',['../df/d24/classdoris_1_1pipeline_1_1_agg_sink_operator.html',1,'doris::pipeline']]],
  ['aggsinkoperatorbuilder_146',['AggSinkOperatorBuilder',['../d2/d6a/classdoris_1_1pipeline_1_1_agg_sink_operator_builder.html',1,'doris::pipeline']]],
  ['aggsourceoperator_147',['AggSourceOperator',['../d8/d4f/classdoris_1_1pipeline_1_1_agg_source_operator.html',1,'doris::pipeline']]],
  ['aggsourceoperatorbuilder_148',['AggSourceOperatorBuilder',['../d2/d76/classdoris_1_1pipeline_1_1_agg_source_operator_builder.html',1,'doris::pipeline']]],
  ['alignednew_149',['AlignedNew',['../dc/de4/structdoris_1_1_aligned_new.html',1,'doris']]],
  ['allocator_150',['Allocator',['../d0/dc1/class_allocator.html',1,'Allocator&lt; clear_memory_, mmap_populate &gt;'],['../d0/dac/classdoris_1_1_path_trie_1_1_allocator.html',1,'PathTrie&lt; T &gt;::Allocator']]],
  ['allocator_3c_20false_20_3e_151',['Allocator&lt; false &gt;',['../d0/dc1/class_allocator.html',1,'']]],
  ['allocatorwithstackmemory_152',['AllocatorWithStackMemory',['../dd/d3f/class_allocator_with_stack_memory.html',1,'']]],
  ['allowempty_153',['AllowEmpty',['../de/dc8/structstrings_1_1_allow_empty.html',1,'strings']]],
  ['alphanum_154',['AlphaNum',['../df/da5/struct_alpha_num.html',1,'']]],
  ['altermaterializedviewparam_155',['AlterMaterializedViewParam',['../d3/dea/structdoris_1_1_schema_change_handler_1_1_alter_materialized_view_param.html',1,'doris::SchemaChangeHandler']]],
  ['analyticsinkoperator_156',['AnalyticSinkOperator',['../d5/da9/classdoris_1_1pipeline_1_1_analytic_sink_operator.html',1,'doris::pipeline']]],
  ['analyticsinkoperatorbuilder_157',['AnalyticSinkOperatorBuilder',['../d0/dd6/classdoris_1_1pipeline_1_1_analytic_sink_operator_builder.html',1,'doris::pipeline']]],
  ['analyticsourceoperator_158',['AnalyticSourceOperator',['../d3/d95/classdoris_1_1pipeline_1_1_analytic_source_operator.html',1,'doris::pipeline']]],
  ['analyticsourceoperatorbuilder_159',['AnalyticSourceOperatorBuilder',['../d4/d8f/classdoris_1_1pipeline_1_1_analytic_source_operator_builder.html',1,'doris::pipeline']]],
  ['and_5f_160',['and_',['../d3/d11/structbase_1_1and__.html',1,'base']]],
  ['andblockcolumnpredicate_161',['AndBlockColumnPredicate',['../d6/df9/classdoris_1_1_and_block_column_predicate.html',1,'doris']]],
  ['andimpl_162',['AndImpl',['../d2/d73/structdoris_1_1vectorized_1_1_functions_logical_detail_1_1_and_impl.html',1,'doris::vectorized::FunctionsLogicalDetail']]],
  ['anyof_163',['AnyOf',['../dc/d8d/classstrings_1_1delimiter_1_1_any_of.html',1,'strings::delimiter']]],
  ['arena_164',['Arena',['../d8/dc2/classdoris_1_1vectorized_1_1_arena.html',1,'doris::vectorized']]],
  ['arenakeyholder_165',['ArenaKeyHolder',['../dc/db7/structdoris_1_1vectorized_1_1_arena_key_holder.html',1,'doris::vectorized']]],
  ['args_166',['args',['../d8/d08/structargs.html',1,'']]],
  ['array_167',['Array',['../d8/df5/classdoris_1_1vectorized_1_1_simd_j_s_o_n_parser_1_1_array.html',1,'doris::vectorized::SimdJSONParser']]],
  ['arrayaggregateimpl_168',['ArrayAggregateImpl',['../d5/d99/structdoris_1_1vectorized_1_1_array_aggregate_impl.html',1,'doris::vectorized']]],
  ['arrayaggregateresultimpl_169',['ArrayAggregateResultImpl',['../db/db0/structdoris_1_1vectorized_1_1_array_aggregate_result_impl.html',1,'doris::vectorized']]],
  ['arrayaggregateresultimpl_3c_20element_2c_20aggregateoperation_3a_3aaverage_20_3e_170',['ArrayAggregateResultImpl&lt; Element, AggregateOperation::AVERAGE &gt;',['../d7/d4a/structdoris_1_1vectorized_1_1_array_aggregate_result_impl_3_01_element_00_01_aggregate_operation_1_1_a_v_e_r_a_g_e_01_4.html',1,'doris::vectorized']]],
  ['arrayaggregateresultimpl_3c_20element_2c_20aggregateoperation_3a_3amax_20_3e_171',['ArrayAggregateResultImpl&lt; Element, AggregateOperation::MAX &gt;',['../db/d48/structdoris_1_1vectorized_1_1_array_aggregate_result_impl_3_01_element_00_01_aggregate_operation_1_1_m_a_x_01_4.html',1,'doris::vectorized']]],
  ['arrayaggregateresultimpl_3c_20element_2c_20aggregateoperation_3a_3amin_20_3e_172',['ArrayAggregateResultImpl&lt; Element, AggregateOperation::MIN &gt;',['../d8/d15/structdoris_1_1vectorized_1_1_array_aggregate_result_impl_3_01_element_00_01_aggregate_operation_1_1_m_i_n_01_4.html',1,'doris::vectorized']]],
  ['arrayaggregateresultimpl_3c_20element_2c_20aggregateoperation_3a_3aproduct_20_3e_173',['ArrayAggregateResultImpl&lt; Element, AggregateOperation::PRODUCT &gt;',['../db/dae/structdoris_1_1vectorized_1_1_array_aggregate_result_impl_3_01_element_00_01_aggregate_operation_1_1_p_r_o_d_u_c_t_01_4.html',1,'doris::vectorized']]],
  ['arrayaggregateresultimpl_3c_20element_2c_20aggregateoperation_3a_3asum_20_3e_174',['ArrayAggregateResultImpl&lt; Element, AggregateOperation::SUM &gt;',['../d9/d08/structdoris_1_1vectorized_1_1_array_aggregate_result_impl_3_01_element_00_01_aggregate_operation_1_1_s_u_m_01_4.html',1,'doris::vectorized']]],
  ['arraycolumnreader_175',['ArrayColumnReader',['../da/dfe/classdoris_1_1vectorized_1_1_array_column_reader.html',1,'doris::vectorized']]],
  ['arraycolumnwriter_176',['ArrayColumnWriter',['../d8/d16/classdoris_1_1segment__v2_1_1_array_column_writer.html',1,'doris::segment_v2']]],
  ['arraycontainsaction_177',['ArrayContainsAction',['../de/d3f/structdoris_1_1vectorized_1_1_array_contains_action.html',1,'doris::vectorized']]],
  ['arraycountequal_178',['ArrayCountEqual',['../d0/d5f/structdoris_1_1vectorized_1_1_array_count_equal.html',1,'doris::vectorized']]],
  ['arrayfield_179',['ArrayField',['../dd/d4e/classdoris_1_1_array_field.html',1,'doris']]],
  ['arrayfilecolumniterator_180',['ArrayFileColumnIterator',['../da/da4/classdoris_1_1segment__v2_1_1_array_file_column_iterator.html',1,'doris::segment_v2']]],
  ['arrayfilterfunction_181',['ArrayFilterFunction',['../d8/dee/classdoris_1_1vectorized_1_1_array_filter_function.html',1,'doris::vectorized']]],
  ['arrayiteratorfunctions_182',['ArrayIteratorFunctions',['../d9/d44/structdoris_1_1_array_iterator_functions.html',1,'doris']]],
  ['arrayjoinimpl_183',['ArrayJoinImpl',['../db/d13/structdoris_1_1vectorized_1_1_array_join_impl.html',1,'doris::vectorized']]],
  ['arraymapfunction_184',['ArrayMapFunction',['../d8/d6a/classdoris_1_1vectorized_1_1_array_map_function.html',1,'doris::vectorized']]],
  ['arraypositionaction_185',['ArrayPositionAction',['../d5/d0c/structdoris_1_1vectorized_1_1_array_position_action.html',1,'doris::vectorized']]],
  ['arrayreverseimpl_186',['ArrayReverseImpl',['../df/dd9/structdoris_1_1vectorized_1_1_array_reverse_impl.html',1,'doris::vectorized']]],
  ['arraysetimpl_187',['ArraySetImpl',['../d7/d3d/structdoris_1_1vectorized_1_1_array_set_impl.html',1,'doris::vectorized']]],
  ['arraytypeinfo_188',['ArrayTypeInfo',['../de/d2f/classdoris_1_1_array_type_info.html',1,'doris']]],
  ['arrayval_189',['ArrayVal',['../df/dc9/classdoris_1_1_array_val.html',1,'doris']]],
  ['arrowfile_190',['ArrowFile',['../d3/dd1/classdoris_1_1_arrow_file.html',1,'doris']]],
  ['arrowreaderwrap_191',['ArrowReaderWrap',['../d1/d82/classdoris_1_1_arrow_reader_wrap.html',1,'doris']]],
  ['asinname_192',['AsinName',['../d7/d6d/structdoris_1_1vectorized_1_1_asin_name.html',1,'doris::vectorized']]],
  ['asserterbase_193',['AsserterBase',['../d9/d62/structbase_1_1_asserter_base.html',1,'base']]],
  ['assertnumrowsoperator_194',['AssertNumRowsOperator',['../d8/d44/classdoris_1_1pipeline_1_1_assert_num_rows_operator.html',1,'doris::pipeline']]],
  ['assertnumrowsoperatorbuilder_195',['AssertNumRowsOperatorBuilder',['../d1/d46/classdoris_1_1pipeline_1_1_assert_num_rows_operator_builder.html',1,'doris::pipeline']]],
  ['async_5frpc_5fcontext_196',['async_rpc_context',['../da/db1/structdoris_1_1async__rpc__context.html',1,'doris']]],
  ['asyncio_197',['AsyncIO',['../d4/d90/classdoris_1_1_async_i_o.html',1,'doris']]],
  ['asyncioctx_198',['AsyncIOCtx',['../dc/d31/structdoris_1_1_async_i_o_ctx.html',1,'doris']]],
  ['atanname_199',['AtanName',['../df/ded/structdoris_1_1vectorized_1_1_atan_name.html',1,'doris::vectorized']]],
  ['atomiccounter_200',['AtomicCounter',['../d8/d60/classdoris_1_1_atomic_counter.html',1,'doris']]],
  ['atomicgauge_201',['AtomicGauge',['../d5/d93/classdoris_1_1_atomic_gauge.html',1,'doris']]],
  ['atomicmetric_202',['AtomicMetric',['../db/de2/classdoris_1_1_atomic_metric.html',1,'doris']]],
  ['atomicops_5fx86cpufeaturestruct_203',['AtomicOps_x86CPUFeatureStruct',['../d6/d73/struct_atomic_ops__x86_c_p_u_feature_struct.html',1,'']]],
  ['atomicstatistics_204',['AtomicStatistics',['../db/d2a/structdoris_1_1io_1_1_atomic_statistics.html',1,'doris::io']]],
  ['atomicwrapper_205',['AtomicWrapper',['../d0/dfb/structdoris_1_1vectorized_1_1_atomic_wrapper.html',1,'doris::vectorized']]],
  ['atomicwrapper_3c_20uint32_5ft_20_3e_206',['AtomicWrapper&lt; uint32_t &gt;',['../d0/dfb/structdoris_1_1vectorized_1_1_atomic_wrapper.html',1,'doris::vectorized']]],
  ['attachtask_207',['AttachTask',['../d3/d74/classdoris_1_1_attach_task.html',1,'doris']]],
  ['authinfo_208',['AuthInfo',['../d4/d61/structdoris_1_1_auth_info.html',1,'doris']]],
  ['autodigit_5fgreater_209',['autodigit_greater',['../d6/d24/structautodigit__greater.html',1,'']]],
  ['autodigit_5fless_210',['autodigit_less',['../d3/d71/structautodigit__less.html',1,'']]],
  ['avg_211',['Avg',['../d1/d02/structdoris_1_1vectorized_1_1_avg.html',1,'doris::vectorized']]],
  ['avgnearestfieldtypetrait_212',['AvgNearestFieldTypeTrait',['../d2/daf/structdoris_1_1vectorized_1_1_avg_nearest_field_type_trait.html',1,'doris::vectorized']]],
  ['avgnearestfieldtypetrait_3c_20decimal128_20_3e_213',['AvgNearestFieldTypeTrait&lt; Decimal128 &gt;',['../dc/d43/structdoris_1_1vectorized_1_1_avg_nearest_field_type_trait_3_01_decimal128_01_4.html',1,'doris::vectorized']]],
  ['avgnearestfieldtypetrait_3c_20decimal128i_20_3e_214',['AvgNearestFieldTypeTrait&lt; Decimal128I &gt;',['../de/d2f/structdoris_1_1vectorized_1_1_avg_nearest_field_type_trait_3_01_decimal128_i_01_4.html',1,'doris::vectorized']]],
  ['avgnearestfieldtypetrait_3c_20decimal32_20_3e_215',['AvgNearestFieldTypeTrait&lt; Decimal32 &gt;',['../dd/d5c/structdoris_1_1vectorized_1_1_avg_nearest_field_type_trait_3_01_decimal32_01_4.html',1,'doris::vectorized']]],
  ['avgnearestfieldtypetrait_3c_20decimal64_20_3e_216',['AvgNearestFieldTypeTrait&lt; Decimal64 &gt;',['../da/d6e/structdoris_1_1vectorized_1_1_avg_nearest_field_type_trait_3_01_decimal64_01_4.html',1,'doris::vectorized']]],
  ['avgnearestfieldtypetrait_3c_20int64_20_3e_217',['AvgNearestFieldTypeTrait&lt; Int64 &gt;',['../d1/d46/structdoris_1_1vectorized_1_1_avg_nearest_field_type_trait_3_01_int64_01_4.html',1,'doris::vectorized']]]
];
